[package]
name = "yew-gloo-storage-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
gloo = "0.5.0"
gloo-storage = "0.2.0"
